import "../styles/globals.scss";
import React from "react";
import type { AppProps } from "next/app";
import { PageContextProvider} from "../contexts/PageContext";
import { AnimatePresence } from "framer-motion";
import Loading from "../components/Loading";
import Header from "../components/Header";
import Head from "next/head";
import CursorFollower from "../components/CursorFollower";

import "../styles/master.scss"

function MyApp({ Component, pageProps, router  }: AppProps) {
  return (
    <>
    <Head>
        <title>Lucas Oliveira - portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    <PageContextProvider>
      <Loading pageRoute={router.route}/>
      <CursorFollower />
      <Header />
      <AnimatePresence mode="wait" initial={false}>
        <Component {...pageProps} key={router.route}/>
      </AnimatePresence>
    </PageContextProvider>
    </>
  );
}

export default MyApp;
