import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { CursorProvider } from "@/contexts/CursorContext";
import { PageContextProvider } from "@/contexts/PageContext";
import { DeviceContextProvider } from "@/contexts/DeviceContext";
import CursorFollower from "@/components/CursorFollower";
import Header from "@/components/Header";
import "@/styles/css/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
          {/* <Loading /> */}
          <CursorFollower />
          <Header />
          {children}
        </AppProviders>
        <SpeedInsights />
      </body>
    </html>
  );
}

function AppProviders({ children }: { children: React.ReactNode }) {
  return (
    <>
      <CursorProvider>
        <PageContextProvider>
          <DeviceContextProvider>
            <LanguageProvider>
              {children}
            </LanguageProvider>
          </DeviceContextProvider>
        </PageContextProvider>
      </CursorProvider>
    </>
  );
}
